name: book_hotel
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^1.2.0+3
  dio: ^5.8.0+1
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  get_it: ^8.0.3
  vnpay_flutter: ^1.0.1
  webview_flutter: ^4.8.0
  shared_preferences: ^2.3.3
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/
    - assets/data/
